<?php echo Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true))->getGroupedHtml() ?>
<div class="clearer"></div>
<div class="acount_wrapper">
<div class="acount-cut-right">

<div style="width:70%; margin: 0 auto;">

<div class="account-title">
  <h2 style="margin-left:50px !important">Contact Us</h2>
<div class="clearer"></div>
</div>
<div class="account-form">
    <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset">
<div style="color:#fff;">
<p>Need Help? </p>
<p>Call Customer Service : 022 6464 6444.</p>
<p>We will respond to most emails within 24 hours. Please fill in the email form below and one of our Customer Care team will get back to you.</p>
<p>&nbsp;</p>

</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>

<ul class="form-list">
        <li class="fields">
                <div class="field">
                    <label for="name" class="required"><?php echo Mage::helper('contacts')->__('Name') ?> <em>*</em></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><?php echo Mage::helper('contacts')->__('Email') ?> <em>*</em></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
      </li>
            <li>
                <label for="telephone" class="required"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text required-entry validate-number2" type="text" />
                </div>
            </li>
            <li class="wide">
              <label for="comment" class="required"><?php echo Mage::helper('contacts')->__('Comment') ?> <em>*</em></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" style="width:500px; min-height:150px; border-radius:5px;"></textarea>
              </div>
            </li>
      </ul>

    <div class="buttons-set">
    <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" style="background:#fff; border:none; width:120px; height:30px; font-size:20px; color:#E96608; text-transform:uppercase; border-radius:5px;"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
   <div class="clearer"></div>       
 <div style="float:left; color:#fff; margin-top:10px;">* Indicates required fields</div>
  <div class="clearer"></div>
 <div style="float:left; padding:5px; background:#FF0000; color:#fff; border-radius:5px; margin-top:5px; ">For your security reasons, do not submit credit card numbers to us through email.</div>
  <div class="clearer"></div>
        
    </div>
</form>
</div>

</div>
<div class="clearer"></div>
</div>
</div>
</div>
