<div style="background:#ECECEC; clear:both; margin-bottom:0px;">


<div class="lys_row1_container">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td>
    <div class="footer-link-left"></div>
    <div class="footer-link-center">
      <h4 style="margin-left:-3px;">Live Your Sport</h4>      
        <a href="<?php echo($this->getBaseUrl()) ?>who-we-are/">Who We Are</a><br />
        <a href="<?php echo($this->getBaseUrl()) ?>why-lys/">Why LYS</a><br />
        <a href="<?php echo($this->getBaseUrl()) ?>our-offering/">Our Offering</a><br />
        <a href="<?php echo($this->getBaseUrl()) ?>lys-philosophy/">LYS Philosophy</a><br />

</div>
    <div class="footer-link-right"></div>
    <div class="footer-link-center">

      <h4 style="margin-left:30px;">Support</h4>
      <a href="<?php echo($this->getBaseUrl()) ?>help/">Help</a><br />
      <a href="<?php echo($this->getBaseUrl()) ?>contact-us/">Contact Us</a><br />
      <a href="<?php echo($this->getBaseUrl()) ?>returns/">Return Policy</a></div>
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
      <h4 style="margin-left:30px;">Orders</h4>
      <a href="<?php echo($this->getBaseUrl()) ?>special-orders/">Special Orders</a><br />
      <a href="<?php echo($this->getBaseUrl()) ?>bulk-orders/">Bulk Orders</a><br />
      <a href="<?php echo($this->getBaseUrl()) ?>payment-options/">Payment Options</a><br />
      </div>
    
    
        <div class="footer-link-right"></div>
    <div class="footer-link-center">
 <h4 style="margin-left:5px;">Pay Securely</h4>
<div style="margin-top:5px; margin-left:5px;"><img src="<?php echo $this->getSkinUrl('images/icons/ccavenue.gif') ?>" border=0 width="120px"></div>
      </div>

    
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
	<h4 style="margin-left:20px;">Powered By</h4>
<div style="margin-top:30px; margin-left:20px;"><img src="<?php echo $this->getSkinUrl('images/icons/verisign.png') ?>" border="0" style="position:relative; top:-12px;"></div>
	
    </div>
      
      
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
 	<h4>Logistics Partners</h4>
<div style="margin-top:30px; margin-left:20px;"><img src="<?php echo $this->getSkinUrl('images/icons/aramex.png') ?>"></div>
    <div style="margin-top:5px; margin-left:20px;"><img src="<?php echo $this->getSkinUrl('images/icons/afl.png') ?>"></div>
	
    </div>
    <!--
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
      <h4 style="margin-left:7px;">Product</h4>
      <a href="#">Sizing Charts</a><br />
      <a href="#">Customization</a><br />
      <a href="#">Trial Kit</a><br />
      <a href="#">Product Care</a><br />
      <a href="#">Warranty &amp; Guarantee</a><br />
      <a href="#">Gift Cards &amp; Vouchers</a>
      </p>
    </div>
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
      <h4 style="margin-left:7px;">Support</h4>
      <a href="#">Help</a><br />
      <a href="#">Security &amp; Privacy</a><br />
      <a href="#">Sales &amp; Refunds</a><br />
      <a href="#">Terms of Use</a><br />
      <a href="#">How to use this site</a><br />
      <a href="#">FAQs</a><br />
      <a href="#">Signup Benefits</a>
      </p>
    </div>
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
      <h4 style="margin-left:-3px;">Live Your Sport</h4>
      <a href="#">Who we are?</a><br />
      <a href="#">Our Philosophy</a><br />
      <a href="#">Why Us?</a><br />
      <a href="#">Shop with Confidence</a><br />
    </div>
    <div class="footer-link-right"></div>
    <div class="footer-link-center">
      <h4>Follow LYS</h4>
      <a href="#">Newsletter</a><br />
      <a href="#">Blog</a><br />
      <a href="#">Facebook</a><br />
      <a href="#">Twitter</a><br />
      <a href="#">Youtube</a>
      </p>
    </div>     -->
    <div class="footer-link-right-extreme"></div>
   

</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><span class="footer_privacy" style="text-align:right"><a href="<?php echo($this->getBaseUrl()) ?>/privacy-policy">Privacy Policy</a> |<a href="<?php echo($this->getBaseUrl()) ?>/contact-us"> Feedback</a></span></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
  </tr>
  <tr>
    <td align="right"><a href="#" target="_blank"><img src="<?php echo $this->getSkinUrl('images/icons/twitter.jpg') ?>" alt="Liveyoursport on Facebook" width="22" height="22" border="0" style="float:right; margin-left:5px;"/></a><a href="http://www.facebook.com/pages/Live-Your-Sport/416609828372517" target="_blank"><img src="<?php echo $this->getSkinUrl('images/icons/fb.jpg') ?>" alt="Liveyoursport on Facebook" width="22" height="22" border="0" style="float:right"/></a></td>
  </tr>
  <tr>
    <td><div style="float:left; margin-left:5px; margin-top:10px; margin-bottom:10px; color:#666">
      Brand & Design Partners
  <div class="abnd" url="http://www.abrandnewday.in/"><a>ABND</a></div>
  </div>
  
  <div style="float:right; color:#666666;  margin-top:10px; margin-bottom:10px; margin-left:-35px; text-align:right;">2012 LiveYourSport.com Ltd<br />All Rights Reserved.
</div>
  
  </td>
  </tr>
</table>



</div>

</div>