

<ul class="sp-methods" id="checkout-payment-method-load">
<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<?php
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>
    <li class="payments_<?php echo $_code ?>">
    <?php if(!$oneMethod): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
        <?php $oneMethod = $_code; ?>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </li>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <dd>
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
<?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
<?php endif; ?>
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
$j("#cash").hide();
$j("#avenue").show();

var online = "li.payments_avenues_standard";
var cash =   "li.payments_cashondelivery";
$j('input[name=payment[method]]').filter('[value="avenues_standard"]').attr('checked', true);

$j(online).addClass('pactive');

$j('input#p_method_cashondelivery').click(function(){
   
  	$j("#avenue").hide();
	$j("#cash").show();
	$j(online).removeClass('pactive');
	$j(cash).addClass('pactive');
	
	
}

);


$j('input#p_method_avenues_standard').click(function(){   
  	$j("#avenue").show();
	$j("#cash").hide();
	$j(cash).removeClass('pactive');
	$j(online).addClass('pactive');
}
);
if(quoteBaseGrandTotal>cashondelivery_max_limit){
$j("input#p_method_cashondelivery").attr('disabled',true);	
$j('li.payments_cashondelivery').click(function(){ 
	$j('.cod_limit_warning').show();
  });

function destroyCod() { 
$j('.cod_limit_warning').hide();
}

}

//]]>
</script>


