<div class="buttons-set" id="shipping-buttons-container">
    <button type="button" class="indibutton" title="<?php echo $this->__('Back') ?>" onclick="openPrevSection()"><span><span><?php echo $this->__('Back') ?></span></span></button>
    <button type="button" class="indibutton" title="<?php echo $this->__('Place Order') ?>" onclick="review.save()"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
</div>