<div class="lysopcstep">
 <?php echo $this->getChildHtml('login_before')?>
<form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
<div class="opclogin">
<h2><?php echo $this->__('Existing Customer') ?></h2>
<div>

<label for="login-email" class="required" ><?php echo $this->__('Email Address') ?> <em>*</em></label>
</div>
<div>         
<input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
</div>    

<div>
<label for="login-password" class="required"><?php echo $this->__('Password') ?> <em>*</em></label>
</div>   
<div>
<input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
</div>  
<div>
<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" ><?php echo $this->__('Forgot your password?') ?></a>
<?php echo $this->getChildHtml('persistent.remember.me'); ?>
</div>
<div>
<input name="context" type="hidden" value="checkout" />
 <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
</div>

</div>
</form>

<div class="opcdivider"></div>



<div class="opcnewcustomer">
<h2><?php echo $this->__('New Customer') ?></h2>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
       
        <?php else: ?>
            <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
            <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
        
        
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control">
                    <label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label> <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
                </li>
                <?php endif; ?>
                <li class="control">
                 <label for="login:register"><?php echo $this->__('Register') ?></label> <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                </li>
            </ul>
                 <p><?php echo $this->__('Register with us for future convenience.') ?></p>

        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
        
        
        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
                </form>
            <?php endif; ?>
            
</div>

</div>




<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
