<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>


<div><?php echo $this->getToolbarHtml() ?></div>




<div>
  <div><div class="track"><div class="thumb"></div></div></div>
		<div class="viewport">
			 <div class="overview">




<div class="category-products">
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
    
    
             <?php $lys_price = number_format($_product->getFinalPrice());?>
            <?php $mrp_price =  number_format($_product->getPrice());?>
            <?PHP $finalprice = Mage::helper('core')->currency($_product->getFinalPrice()); ?>
    
    
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" width="170" height="170" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                	 <h2><?php echo $_product->getAttributeText('manufacturer');?></h2>
             <?php $maxLength = 65; ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, strtolower(substr($_product->getName(),0,$maxLength)), 'name') ?></a>
            
               
                   
                   
                   
                   
                   
                   
                   
                   
                     <div class="clearer"></div>
            <div class="grid-price mrp-color" id="grid-price">
            <h4> <?php echo 'LYS Rs. '.$lys_price; ?></h4>
             </div>
             <div class="clearer"></div>
            <div class="grid-discount">
            
         
             <div class="clearer"></div>
             <?php if ($lys_price != $mrp_price): ?>
             <div class="grid-price-mrp"><h2>MRP Rs. <?php echo $mrp_price; ?></h2></div>
             <?php endif; ?>
              <div class="clearer"></div>
             
             
			<?php
             $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());
             $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
             if ($_regularPrice != $_finalPrice):
             $getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);
             $finalpercentage = 100 - $getpercentage;     
            echo '<h5 class="grid-price">YOU SAVE '.number_format($finalpercentage, 0).'%</h5>' ;     
             endif;?>           
            </div>
            
            <div class="clearer"></div>
            
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                   
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                       
                    </div>

                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>
    
    
    
    
    
    

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
        
        
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(170); ?>" width="170" height="170" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            
          
          <div class="product-info-wrapper">
          
          <h2><?php echo $_product->getAttributeText('manufacturer');?></h2>
          
            <div class="grid-name">
            <?php $maxLength = 25; ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, strtolower(substr($_product->getName(),0,$maxLength)), 'name') ?></a>
            </div>
            
            
            <?php $lys_price = number_format($_product->getFinalPrice());?>
            <?php $mrp_price =  number_format($_product->getPrice());?>
            <?PHP $finalprice = Mage::helper('core')->currency($_product->getFinalPrice()); ?>
            
			  <div class="clearer"></div>
            <div class="grid-price mrp-color" id="grid-price">
            <h4> <?php echo 'LYS Rs. '.$lys_price; ?></h4>
             </div>
             <div class="clearer"></div>
            <div class="grid-discount">
            
         
             <div class="clearer"></div>
             <?php if ($lys_price != $mrp_price): ?>
             <div class="grid-price-mrp"><h2>MRP Rs. <?php echo $mrp_price; ?></h2></div>
             <?php endif; ?>
              <div class="clearer"></div>
             
             
			<?php
             $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());
             $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
             if ($_regularPrice != $_finalPrice):
             $getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);
             $finalpercentage = 100 - $getpercentage;     
            echo '<h5 class="grid-price">YOU SAVE '.number_format($finalpercentage, 0).'%</h5>' ;     
             endif;?>           
            </div>
            
            <div class="clearer"></div>
            

          </div>  
            
            
            
            </li>
            
            
            
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>


</div>
                
			</div>
		</div>
	</div>	
    
<!-- Show Pagination Info -->
<div><?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_bottom.phtml')->toHtml(); ?> </div>    
    
    
    <?php endif; ?>
	
    
    
    <!-- This is for the lys scrollbars to ignite -->
<script type="text/javascript">
		var $lys_scroll = jQuery.noConflict();
			$lys_scroll(document).ready(function(){
			$lys_scroll('#scrollbar1').tinyscrollbar();	
			});
</script>	
