<?php $_helper = $this->helper('catalog/output'); ?>
<?php
$url = Mage::helper('core/url')->getCurrentUrl();
$counts = Mage::helper('aureatelabs')->getSocialCount($url);
?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<!-- Product box container -->
<div class="clearer"></div>
<div class="product-box-container" >

    <div class="fl product-box-left">
        <div class="product-box-head">
            <h4 class="left prod-manuf-name"><span class="prod-manuf"><?php echo $_product->getAttributeText('manufacturer'); ?></span> <span class="prod-name"><?php echo $_product->getName(); ?></span></h4>
            <h4 class="right prod-sku"><?php echo $this->__('Item Code ').nl2br($_product->getSku()) ?></h4>
        </div>
    </div>
    <div class="product-box-content">
        <!-- Right Side -->
        <div class="prod-box-right">
            <div class="prod-right-sub1">
                <!-- Display none to this for configurables total -->
                <div style="display:none">
                    <?php echo $this->getPriceHtml($_product) ?>
                </div>
                <!-- -->

                <div class="productname-box box1">
                    <div class="inner">
                        <?php $lys_price = number_format($_product->getFinalPrice(('price'), 0)); ?>
                        <?php $mrp_price = number_format($_product->getPrice(), 0); ?>

                        <h3>LYS Price Rs. <?php echo $lys_price; ?></h3>
                        <?php if ($lys_price != $mrp_price): ?>
                            <h2><span><?php echo $this->__('MRP : Rs. ').$mrp_price; ?></span></h2>
                        <?php endif; ?>


                        <?php
                        $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());
                        $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
                        if ($_regularPrice != $_finalPrice):
                            $getpercentage = number_format($_finalPrice / $_regularPrice * 100, 2);
                            $finalpercentage = 100 - $getpercentage;
                            echo '<h1>You Save ' . number_format($finalpercentage, 0) . '%</h1>';
                        endif;
                        ?>
                    </div>
                </div>
                <div class="productname-box box2">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/shipping.gif') ?>" alt="Shipping" />
                        <?php if (!$_product->isSaleable()): ?><div class="prod-out-of-stock">Currently Out of Stock</div><?php endif; ?>
                        <h5>1-<?php echo $_product->getShippingDays()>0 ? $_product->getShippingDays() : 7 ?> Business Days</h5>
                    </div>
                </div>
                <div class="productname-box box3">
                    <div class="inner">
                        <?php echo $this->getChildHtml('product_attributes_placeholder'); ?>
                        <h5><?php echo $this->__('Authentic Product')?></h5>
                    </div>
                </div>
                <div class="clearer"></div>

                <!-- Product Attributes -->
                <div class="productprice-box box4">

                    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                        <div class="no-display">
                            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                            <input type="hidden" name="related_product" id="related-products-field" value="" />
                        </div>
                        <?php echo $this->getTierPriceHtml() ?>
                        <?php //echo $this->getChildHtml('extrahint')  ?>

                        <?php if (!$this->hasOptions()): ?>
                        <div class="options">

                            <div class="dummyopt">
                                <label><?php echo $this->__('Size')?></label>
                                <select name="" disabled="disabled">
                                    <option>No Options</option>
                                </select>
                            </div>

                            <div  class="dummyopt">
                                <label><?php echo $this->__('Color')?></label>
                                <select name="" disabled="disabled">
                                    <option>No Options</option>
                                </select>
                            </div>
                        </div>
                        <div class="addto">
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <h4><p><?php echo $this->__('Total : LYS Price ').$lys_price; ?></p></h4>
                            <?php //endif;  ?>
                            <?php echo $this->getChildHtml('addto') ?>
                        </div>
                        <?php endif;?>


                        <?php echo $this->getChildHtml('other'); ?>

                        <?php //if ($_product->isSaleable() && $this->hasOptions()):
                        if ($this->hasOptions()):
                        ?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                        <?php endif; ?>

                        <?php //if ($_product->isSaleable() && $this->hasOptions()):
                        if ($this->hasOptions()):
                        ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                        <?php endif; ?>
                    </form>             
                </div>
                <!-- -->
            </div>
            <div class="prod-right-sub2">
                <div class="productname-box box5">
                    <div class="inner">
                        <?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
                        <a href="<?php if($_compareUrl) echo $_compareUrl; else echo '#';?>">
                            <img src="<?php echo $this->getSkinUrl('images/lys/compare.jpg') ?>" alt="Compare" />
                        </a>
                        <h5><?php echo $this->__('Compare')?></h5>
                    </div>
                </div>
                <div class="productname-box box6">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/view.jpg') ?>" alt="Views" />
                        <h5><?php echo $this->__('Views')?></h5>
                        <h5><?php
                            $p_id = $_product->getId();
                            echo Mage::getResourceModel('reports/product_collection')->getProductViews($p_id);
                            ?>
                        </h5>
                    </div>
                </div>
                <div class="productname-box box6">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/reviews.jpg') ?>" alt="Reviews" />
                        <h5><?php echo $this->__('Reviews')?></h5>
                        <h5>
                            <?php echo $reviewCount = $_product->getReviewCount() ? $_product->getReviewCount(): 0;?>
                        </h5>
                    </div>
                </div>
                <div class="productname-box box6">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/twitter.jpg') ?>" alt="Twitter" />
                        <h5><?php echo $this->__('Tweets')?></h5>
                        <h5>
                            <?php echo $counts["Twitter"] ?>
                        </h5>
                    </div>
                </div>
                <div class="productname-box box6">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/facebook.jpg') ?>" alt="Facebook" />
                        <h5><?php echo $this->__('Likes')?></h5>
                        <h5>
                            <?php echo $counts["Facebook"]["total_count"] ?>
                        </h5>
                    </div>
                </div>
                <div class="productname-box box6">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/mail.jpg') ?>" alt="Message" />
                        <h5><?php echo $this->__('Share')?></h5>
                        <h5>
                            <?php echo $reviewCount = $_product->getReviewCount() ? $_product->getReviewCount(): 0;?>
                        </h5>
                    </div>
                </div>
                <div class="productname-box box6">
                    <div class="inner">
                        <img src="<?php echo $this->getSkinUrl('images/lys/pinit.jpg') ?>" alt="Pin it" />
                        <h5><?php echo $this->__('Pin it')?></h5>
                        <h5>
                            <?php echo $counts['Pinterest']?>
                        </h5>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Right Side -->
        <div style="float:left; background:#ececec; width:442px;">
            <!-- Product Image -->
            <div class="product-box-pic">
                <div class="product-img-box">
                    <?php echo $this->getChildHtml('media') ?>
                </div>

            </div>
            <!-- -->
        </div>
        <div class="clearer"></div>
        <div class="product-info-tab">
            <div class="product-box-head2" style="margin-top:10px;">
                <h4>Features</h4>
            </div>
            <div class="product-box-content2">  
                <div style="position:relative">
                    <div id="scrollbar">
                        <div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
                        <div class="viewport">
                            <div class="overview">
                                <div>
                                    <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html): ?>
                                        <div class="product-desc">
                                            <?php if ($title = $this->getChildData($alias, 'title')): ?>
                                                <?php echo $this->escapeHtml($title); ?>
                                            <?php endif; ?>
                                            <?php echo $html; ?>
                                        </div>
                                    <?php endforeach; ?>
                                    <?php echo $this->getChildHtml('upsell_products') ?>
                                    <?php echo $this->getChildHtml('product_additional_data') ?>
                                </div>
                                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                                <?php
                                $attributeSetName = Mage::getModel('eav/entity_attribute_set')->load($_product->getAttributeSetId())->getAttributeSetName();

                                if ($attributeSetName == "Decathlon Product") {
                                    $attributes = $_product->getAttributes();
                                    
                                    for($i=1;$i<13;$i++){
                                        $attributetitle[$i] = $attributes["attributetitle$i"]->getFrontend()->getValue($_product);
                                        $attributevalue[$i] = $attributes["attributevalue$i"]->getFrontend()->getValue($_product);
                                        if($attributevalue[$i]){
                                            echo '<h3>' . $attributetitle[$i] . '</h3>';
                                            echo '<a class="overviewdescription">' . $attributevalue[$i] . '</a>';
                                        }
                                        else
                                            break;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearer"></div>
        <div class="pros">
            <?php echo $this->getChildHtml('product_attributes_pros'); ?>
        </div>
        <div class="clearer"></div>


        </div>
        <!-- End of left side -->
        <!-- -->
        <div class="clearer" style="margin-bottom:40px;"></div>
    </div>



</div>
<!-- End of Product box container -->

<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;


            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>

<script type="text/javascript"> 
    $j("#product_view_lys ul").idTabs(); 
</script>

