<div style="padding-top:23px;"></div>
<h3>Brands We Love</h3>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>brands/where/manufacturer/Prince.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Prince</span></a>
</li>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>brands/where/manufacturer/Tecnifibre.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Tecnifibre</span></a>
</li>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>brands/where/manufacturer/Yonex.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Yonex</span></a>
</li>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>brands/where/manufacturer/SG.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">SG</span></a>
</li>



<h3>Sports We Love</h3>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>sports/where/sport-name/cricket.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Cricket</span></a>
</li>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>sports/where/sport-name/tennis.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Tennis</span></a>
</li>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>sports/where/sport-name/squash.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Squash</span></a>
</li>
<li>
<a  href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>sports/where/sport-name/badminton.html" title=""><span style="color:#006d9b !important; text-transform:uppercase">Badminton</span></a>
</li>






