<ul>
<li> <a href="{{store url="furniture.html"}}"><img src="{{skin url='images/pic-1.png}}" alt="" /></a>
<div class="banned_slide_content"><img src="{{skin url='images/proname.png}}" alt="" />
<p class="title">Business Destop PC1</p>
<div class="cls_desc">This is where the slider will change.
<div class="cls_btn"><a href="{{store url="electronics.html"}}"><img src="{{skin url='images/btn_prodetail.png}}" border="0" alt="" /></a> <a href="#"><img src="{{skin url='images/btn_buynow.png}}" border="0" alt="" /></a></div>
</div>
</div>
</li>
<li> <a href="{{store url="furniture.html"}}"><img src="{{skin url='images/pic-2.png}}" alt="" /></a>
<div class="banned_slide_content"><img src="{{skin url='images/proname.png}}" alt="" />
<p class="title">Business Destop PC2</p>
<div class="cls_desc">Combines a solid-state hard drive, a smaller footprint and energy-efficient  features with a long lifecycle and image stability for up to 15 months. Show here with an optional integrated work center...
<div class="cls_btn"><a href="{{store url="furniture.html"}}"><img src="{{skin url='images/btn_prodetail.png}}" border="0" alt="" /></a> <a href="#"><img src="{{skin url='images/btn_buynow.png}}" border="0" alt="" /></a></div>
</div>
</div>
</li>
<li> <a href="{{store url="furniture.html"}}"><img src="{{skin url='images/pic-3.png}}" alt="" /></a>
<div class="banned_slide_content"><img src="{{skin url='images/proname.png}}" alt="" />
<p class="title">Business Destop PC</p>
<div class="cls_desc">Combines a solid-state hard drive, a smaller footprint and energy-efficient  features with a long lifecycle and image stability for up to 15 months. Show here with an optional integrated work center...
<div class="cls_btn"><a href="{{store url="furniture.html"}}"><img src="{{skin url='images/btn_prodetail.png}}" border="0" alt="" /></a> <a href="#"><img src="{{skin url='images/btn_buynow.png}}" border="0" alt="" /></a></div>
</div>
</div>
</li>
<li> <a href="{{store url="furniture.html"}}"><img src="{{skin url='images/pic-4.png}}" alt="" /></a>
<div class="banned_slide_content"><img src="{{skin url='images/proname.png}}" alt="" />
<p class="title">Business Destop PC3</p>
<div class="cls_desc">Combines a solid-state hard drive, a smaller footprint and energy-efficient  features with a long lifecycle and image stability for up to 15 months. Show here with an optional integrated work center...
<div class="cls_btn"><a href="{{store url="furniture.html"}}"><img src="{{skin url='images/btn_prodetail.png}}" border="0" alt="" /></a> <a href="#"><img src="{{skin url='images/btn_buynow.png}}" border="0" alt="" /></a></div>
</div>
</div>
</li>
</ul>
