<div id="lys_placeholder">
			<div class="cols col1"  url="http://liveyoursport.com/index.php/sports/cricket.html/">
            	
              <div class="col_cuts"></div>
			</div>
			
			<div class="cols col2" url="http://liveyoursport.com/index.php/sports/tennis.html/">
			
			
				  <div class="col_cuts"></div>
  </div>
			
			
			<div class="cols col3" url="http://liveyoursport.com/index.php/sports/squash.html/">
			
		
            <div class="col_cuts"></div>
			</div>
			
			<div class="cols col4" url="http://liveyoursport.com/index.php/returns/">
           
			

			<div class="col_cuts"></div>
  </div>
</div>
