<?php
$quotes[] = 'I think sportsmanship is knowing that it is a game, that we are only as a good as our opponents, and whether you win or lose, to always give 100 percent. - <span>Sue Wicks</span>';
$quotes[] = 'I would advise all youths aspiring to athletic fame or a professional career to practice clean living, fair play and good sportsmanship. - <span>Major Taylor</span>';
$quotes[] = 'I have missed more than 9,000 shots in my career, lost almost 300 games, missed the game-winning shot 26 times. I have failed over and over again in my life. That is why I succeed. - <span>Michael Jordan</span>';
$quotes[] = 'Champions keep playing until they get it right. - <span>Billie Jean King</span>';
$quotes[] = 'It does not matter how many times you get knocked down, but how many times you get up. - <span>Vince Lombardi</span>';
$quotes[] = "I never thought about losing, but now that it's happened, the only thing is to do it right. - <span>Muhammed Ali</span>";
$quotes[] = 'The man who can drive himself farther once the effort gets painful is the man who will win. - <span>Sir Roger Bannister</span>';
$quotes[] = "It's the lack of faith that makes people afraid of meeting challenges, and I believe in myself. - <span>Muhammed Ali</span>";
$quotes[] = "The Six W's: Work will win when wishing won't. -Todd Blackledge Character never quits; & with patience & persistence; Dreams do come true. - <span>Pete Maravich</span>";
$quotes[] = "Victory belongs to the most persevering. – <span>Napoleon</span>";
$quotes[] = "If you aren't going all the way, why go at all? - <span>Joe Namath</span>";
$quotes[] = "Success isn't something that just happens - success is learned, success is practiced and then it is shared. -<span>Sparky Anderson</span>";
$quotes[] = "When anyone tells me I can't do anything, I'm just not listening any more.- <span>Florence Griffith Joyner</span>";
$quotes[] = "Success is never final, failure is never fatal. It's courage that counts. - <span>John Wooden</span>";
$quotes[] = "Some people dream of success... others stay awake to achieve it.";
$quotes[] = "One of the trademarks of a champion is that he can outlast you. - <span>Lou Brock</span>";
$quotes[] = "If you are determined enough & willing to pay the price, you can get it done. - <span>Mike Ditka</span>";
$quotes[] = "In life, we choose whether or not we want to be a winner or a loser. - <span>Patrick Boles</span>";
$quotes[] = "Success is about having, excellence is about being. Success is having money & fame, but excellence is being the best you can be. - <span>Mike Ditka</span>";
$quotes[] = "Life is a gift. Never take it for granted. - <span>Sasha Azevedo</span>";
$quotes[] = "A winner never stops trying. - <span>Tom Landry</span>";
$quotes[] = "It's not over when your losing terribly... its over when you quit. – <span>Unknown</span>";
$quotes[] = "Things turn out best for the people who make the best of the way things turn out. - <span>John Wooden</span>";
$quotes[] = "Setting a goal is not the main thing. It is deciding how you will go about achieving it & staying with that plan. - <span>Tom Landry</span>";
$quotes[] = "We have two options, medically & emotionally: give up, or Fight Like Hell. - <span>Lance Armstrong</span>";
$quotes[] = "I've failed over & over & over again in my life & that is why I succeed. - <span>Michael Jordan</span>";
$quotes[] = "Adversity causes some men to break; others to break records.";
$quotes[] = "Success is peace of mind which is a direct result of knowing u did your best to become the best that u are capable of being. - <span>John Wooden</span>";
$quotes[] = "You don't always get what you wish for, you get what you work for.";
$quotes[] = "Never let the fear of striking out get in your way. - <span>Babe Ruth</span>";
$quotes[] = "The resistance that you fight in the gym & the resistance that you fight in life can only build a strong character. - <span>Arnold Schwarzenegger</span>";
$quotes[] = "You should never want to be perfect, he who is perfect can never get any better. - <span>Ashley M.L.</span>";
$quotes[] = "An athlete cannot run with money in his pockets. He must run with hope in his heart and dreams in his head. - <span>Emil Zatopek</span>";
$quotes[] = "The winner ain't the one with the fastest car its the one who refuses to lose. - <span>Dale Earnhardt</span>";
$quotes[] = "You don't win once in a while, you don't do things right once in a while, you do them right all the time. Winning is habit. - <span>Vince Lombardi</span>";
$quotes[] = "You can motivate by fear, & u can motivate by reward. But both those are temporary. The only lasting thing is self motivation.- <span>Homer Rice</span>";
$quotes[] = "The only way to maximize potential for performance is to be calm in the mind. - <span>Brian Sipe</span>";
$quotes[] = "Everybody pulls for David, nobody roots for Goliath. - <span>Wilt Chamberlain</span>";
$quotes[] = "I can accept failure, everyone fails at something. But I can't accept not trying. - <span>Michael Jordan</span>";
$quotes[] = "Today I will do what others won't, so tomorrow I can accomplish what others can't.";
$quotes[] = "Some people want it to happen, some wish it would happen, others make it happen. - <span>Michael Jordan</span>";
$quotes[] = "There may be people that have more talent than you, but there's no excuse for anyone to work harder than you do. - <span>Derek Jeter</span>"; 
$quotes[] = "Pain is only temporary but victory is forever. - <span>Jeremy H</span>";
$quotes[] = "If you don't invest very much, then defeat doesn't hurt very much and winning is not very exciting. - <span>Dick Vermeil</span>";
$quotes[] = "You have to believe in yourself when no one else does- that makes you a winner right there. - <span>Venus Williams</span>";
$quotes[] = "Gold medals aren't really made of gold. They're made of sweat, determination, & a hard-to-find alloy called guts. - <span>Dan Gable</span>";
$quotes[] = "One man practicing sportsmanship is far better than a hundred teaching it. - <span>Knute Rockne</span>";
$quotes[] = "If winning isn't everything, why do they keep score? - <span>Vince Lombardi</span>";
$quotes[] = "There is no glory in practice, but without practice, there is no glory. – <span>Unknown</span>";
$quotes[] = "The spirit, the will to win, & the will to excel are the things that endure. - <span>Vince Lombardi</span>";
$quotes[] = "We do not quit playing because we grow old, we grow old because we quit playing.- <span>Oliver Wendell Holmes</span>";
$quotes[] = "Don't count the days, make the days count - <span>Muhammad Ali</span>";
$quotes[] = "Pain is nothing compared to what it feels like to quit. - <span>Author Unknown</span>";
$quotes[] = "Football is an honest game. It's true to life. It's a game about sharing. Football is a team game. So is life. - <span>Joe Namath</span>";
$quotes[] = "The more you sweat in practice, the less you bleed in battle. - <span>Author Unknown</span>";
$quotes[] = "The important thing is not winning, it's making everyone else lose. - <span>stacy aguilar</span>";
$quotes[] = "Resolve never to quit, never to give up, no matter what the situation. - <span>Jack Nicklaus</span>";
$quotes[] = "One man can be a crucial ingredient on a team, but one man cannot make a team. - <span>Kareem Abdul-Jabbar</span>";
$quotes[] = "In my mind, I'm always the best. If I walk out on the court & I think the next person is better, I've already lost. - <span>Venus Williams</span>";
$quotes[] = "The difference between the impossible and the possible lies in a man's determination. - <span>Tommy Lasorda</span>";
$quotes[] = "When you win, say nothing, when you lose, say less. - <span>Paul Brown</span>";
$quotes[] = "It does not matter how many times you get knocked down, but how many times you get up. - <span>Vince Lombardi</span>";
$quotes[] = "Sure the fight was fixed. I fixed it with a right hand. - <span>George Foreman</span>";
$quotes[] = "The harder you work, the harder it is to surrender. - <span>Vince Lombardi</span>";
$quotes[] = "If you're not making mistakes, then you're not doing anything. - <span>John Wooden</span>";
$quotes[] = "Winners don't wait for chances, they take them. – <span>Unknown</span>";
$quotes[] = "If you aren't fired with enthusiasm, you will be fired with enthusiasm. - <span>Vince Lombardi</span>";




$random_number = rand(0,count($quotes)-1);?>

<div class="random_quote_wrapper">

<div class="quote_left">
<img src="<?php echo($this->getSkinUrl('images/icons/comma-left.png')) ?>" width="120" height="73" />
</div>

<div class="random_quotes" style="text-transform:uppercase; margin-right:5px;"><?php echo $quotes[$random_number]; ?></div>

<div class="quote_right">
<img src="<?php echo($this->getSkinUrl('images/icons/comma-right.png')) ?>" width="120" height="73" />
</div>

<div class="clearer"></div>

</div>


