<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
      <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="input-text" style="font-family:Verdana, Geneva, sans-serif; font-style:normal"/>
   
        <br />
  
<div style="text-align:center; color:#848383; margin-top:15px;  width:350px; text-align:center; font-size:10px;">CUSTOMER SERVICE NUMBER - 022 6464 6444 (10am - 7pm)  
  
  <!-- <span style="float:right; margin-right:30px;">Request a call back</span> -->
  
  
  </div>  
  
  
      <div id="search_autocomplete" class="search-autocomplete"></div>
      <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
    </div>
</form>
