<div class="mini-cart-layer">
	<?php if ($this->getIsNeedToDisplaySideBar()):?>
		<div class="top-cart">
			<?php $_cartQty = $this->getSummaryCount() ?>
			<?php if ($_cartQty > 0): ?>
				<?php $_myCart = $this->__('My Locker (%s)', $_cartQty) ?>
			<?php else: ?>
				<?php $_myCart = $this->__('My Locker (0)') ?>
			<?php endif ?>
			
			<?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()):?>
				<div class="block-title no-items">
					<ul class="links cart-link">
						<li><a href="<?php echo $this->getUrl('checkout/cart'); ?>" rel="nofollow"><?php echo $_myCart ?></a></li>
					</ul>
				</div>
			<?php else:?>
				<div class="block-title<?php if(!$_cartQty) { echo (' no-items'); } ?>">
					<span id="cartHeader"><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $_myCart ?></a></span>
				</div>
				<div id="topCartContent" class="block-content" style="display:none">
					<div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
						<?php $_items = $this->getRecentItems() ?>
						<?php if(count($_items)): ?>
							<p class="block-subtitle">
								<span onclick="toggleTopCart();" class="close-btn"><?php echo $this->__('Close'); ?></span>
								<?php echo $this->__('Recently added item(s)') ?>
							</p>
							<ol id="mini-cart" class="mini-products-list" style="max-height:250px;overflow:auto;">
								<?php foreach($_items as $_item): ?>
									<?php echo $this->getItemHtml($_item) ?>
								<?php endforeach; ?>
							</ol>
							<script type="text/javascript">decorateList('mini-cart', 'none-recursive')</script>
						<?php else: ?>
							<p class="block-subtitle">
								<span onclick="toggleTopCart()" class="close-btn"><?php echo $this->__('Close'); ?></span>
									<?php echo $this->__('Recently added') ?>
							</p>
							<p class="cart-empty">
								<?php echo $this->__('You have no items in your locker.') ?>
							</p>
						<?php endif ?>
						<?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                                
							<div class="actions">
								<a href="<?php echo $this->getUrl('checkout/cart'); ?>" rel="nofollow"><?php echo $this->__('Go to Locker') ?></a>
								<br /><br />
                                <div style="text-align:center;">
                                <button class="locker-checkout" type="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                                <hr />
                                <p>Your purchase qualifies for FREE Home Delivery.</p>
								</div>
                            </div>
						<?php endif ?>
					</div>
				</div>
			<?php endif;?>
		</div>
	<?php endif;?>
</div>

<?php if($this->getRequest()->getParam('updated')): ?>
<script type="text/javascript">
// <![CDATA[ 
    $j = jQuery.noConflict();
    $j(document).ready(function(){
        $j('.ajaxcartpro_progress').fadeOut();
        $j('.ajaxcartpro_progress').css('display','none');
        $j(".top-cart > .block-title").addClass('mini-cart-active');
        $j('#topCartContent').slideDown('slow', function() {
            $j('#topCartContent').delay(3000).slideUp('slow', function(){
                $j(".top-cart > .block-title").removeClass('mini-cart-active');
            });
        });
    });
</script>
<?php endif;?>
<script type="text/javascript">
// <![CDATA[ 
    jQuery(document).ready(function(){
            jQuery('.mini-cart-layer .top-cart .block-title #cartHeader').click(function(){
                    toggleTopCart();
            });

            jQuery('.mini-cart-layer .top-cart .block-title #cartHeader').mouseover(function(){
                    clearTimeout(timer);
            }).mouseout(function(){
                    startTimer();
            });

            jQuery("#topCartContent").mouseover(function() {
                    clearTimeout(timer);
            }).mouseout(function(){
                    startTimer();
            });


            $j("#afterlogin").mouseover(function(){
            $j(".returns").hide();
            $j("#lyslocker").hide();
            });
            $j("#afterlogin").mouseout(function(){
            $j(".returns").show();
            $j("#lyslocker").show();
            });
    });
// ]]>
</script>