<?php
/*$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);*/

$_item = $this->getItem();
$_product= Mage::getSingleton('catalog/product')->load($_item->getProductId());
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item">
	<?php if ($this->hasProductUrl()): ?>
		<a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(70, 70)->setWatermarkSize('30x10'); ?>" width="70" height="70" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></a>
	<?php else: ?>
		<span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(70, 70)->setWatermarkSize('30x10'); ?>" width="70" height="70" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></span>
	<?php endif; ?>
	<div class="product-details">
		<p class="product-name">
			<?php if ($this->hasProductUrl()): ?>
				<a href="<?php echo $this->getProductUrl() ?>">
			<?php endif; ?>
				<?php echo $this->htmlEscape($this->getProductName()) ?>
			<?php if ($this->hasProductUrl()): ?>
				</a>
			<?php endif; ?>
		</p>
        
		<p class="product-name">
			<?php if ($this->hasProductUrl()): ?>
				<a href="<?php echo $this->getProductUrl() ?>">
			<?php endif; ?>
				QTY: <?php echo $this->getQty() ?>

			<?php if ($this->hasProductUrl()): ?>
				</a>
			<?php endif; ?>
		</p>
        <p class="cart-top-price">
        	<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
		</p>
    	<a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');" class="top-btn-remove"></a>
	</div>
</li>