<div style="border-top:3px solid #E96607; padding-top:5px;">
<?php if($this->getCollection()->getSize()): ?>

<div style="float:left; font-weight:bold; color:#000; font-size:10px;"> <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Showing %s to %s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
</div>            
  

 <div class="pager" style="float:right"><?php echo $this->getPagerHtml() ?></div>
 <div class="clearer"></div>

<?php endif ?>
</div>
